#!/usr/bin/python3

import sys
import time

start_time = time.time()

with open(sys.argv[1]) as f:
    for line in f:
        n = int(line)
        for i in range(2, int(n**0.5)+1):
            if n % i == 0:
                p = i
                q = n // i
                print(f"{n}={p}*{q}")
                break

end_time = time.time()
if (end_time - start_time) > 5:
    print("Time limit exceeded")
    sys.exit(1)
