#!/usr/bin/python3

import time
import sys

start_time = time.time()  

def get_factors(n):
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return i, n//i
    return n, 1

if __name__ == "__main__":
    with open(sys.argv[1]) as f:
        for line in f:
            n = int(line)
            p, q = get_factors(n)
            print(f"{n}={p}*{q}")

    end_time = time.time()
    if (end_time - start_time) > 5:
        print("Time limit exceeded")
        sys.exit(1)
