#!/usr/bin/python3

import math
import sys
import time

start = time.time()

def is_prime(n):
    if n == 2:
        return True  
    if n % 2 == 0 or n <= 1:
        return False

    sqr = int(math.sqrt(n)) + 1
    for divisor in range(3, sqr, 2):
        if n % divisor == 0:
            return False
    return True

def get_factors(n):
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0 and is_prime(i):
            return i, n//i

if __name__ == '__main__':
    input_file = sys.argv[1]
    with open(input_file) as f:
        n = int(f.read())
        p, q = get_factors(n)
        print(f"{n}={p}*{q}")

    end = time.time()
    if (end - start) > 5:
        print("Time limit exceeded")   
        sys.exit(1)
