#!/usr/bin/python3

import sys
import random
import time

def is_prime(num):
    if num <= 1:
        return False
    if num <= 3:
        return True
    if num % 2 == 0 or num % 3 == 0:
        return False
    i = 5
    while i * i <= num:
        if num % i == 0 or num % (i + 2) == 0:
            return False
        i += 6
    return True

def factorize_rsa(num):
    for i in range(2, num + 1):
        if num % i == 0 and is_prime(i):
            j = num // i
            if is_prime(j):
                return (i, j)
    return None

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        sys.exit(1)

    start_time = time.time()

    for line in lines:
        num = int(line.strip())
        factors = factorize_rsa(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")

        if time.time() - start_time > 5:
            print("Time limit exceeded")
            sys.exit(1)
